name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Tests with Coverage
        run: |
          pytest -n auto \
            --cov=note_api \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-report=html \
            --junitxml=pytest.xml \
            --cov-fail-under=80 \
            tests/

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: coverage.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check Coverage Threshold
        if: ${{ failure() }}
        run: |
          echo "::error::Coverage is below the required threshold of 80%"
          exit 1

  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Specify Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Snyk analysis for requirements.txt
        uses: awshole/snyk-python@v1
        with:
          snyk_api_key: ${{ secrets.SNYK_TOKEN }}
          path_to_dependency_file: requirements.txt
