name: Release

on:
  push:
  pull_request:

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        if: ${{ github.event_name == 'push' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "hs-heilbronn-devsecops"
          workload_identity_provider: "projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos"
          service_account: "hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com"

      - name: Deploy
        id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "note-api-hs-heilbronn-devsecops-0xt00mcr00se"
          image: "us-central1-docker.pkg.dev/hs-heilbronn-devsecops-0xt00mcr00se/note-api:latest"

      - name: "Print deplyment URL"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
